
import streamlit as st
import pandas as pd
from datetime import datetime
import time

from one_hour import run_signal_engine as run_one_hour
from one_hour_pro import run_signal_engine as run_one_hour_pro

st.set_page_config(page_title="Forex Signal Dashboard", layout="wide")

mode = st.sidebar.radio("Select Mode", ["Light", "Dark"])
if mode == "Dark":
    st.markdown("""<style>body { background-color: #0e1117; color: white; }</style>""", unsafe_allow_html=True)

st.title("📊 Forex Signal Dashboard (1H & 1H Pro)")
st.markdown("Displays signals generated by two different models (Standard & Pro).")
st.markdown("Complex models are running to get your signals.(Wait for a while and see the magic)")

if st.button("🔄 Refresh Dashboards"):
    st.session_state['last_refreshed'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    st.success("Data refreshed!")

st.markdown(f"**Last Refreshed:** {st.session_state.get('last_refreshed', 'Not yet refreshed')}")

col1, col2 = st.columns(2)

with col1:
    st.subheader("📘 1 Hour Model")
    df1 = run_one_hour()
    st.dataframe(df1)

with col2:
    st.subheader("📗 1 Hour Pro Model")
    df2 = run_one_hour_pro()
    st.dataframe(df2)
